Repository PainsPerdus/gboi-rocket, pull requests merged in 2020-06, with the labels that each got.

#19 Create 2020-06-23-Sound1.md
  _posts/2020-06-23-Sound1.md
Labels: sound

#23 Collision solver
  doc/CollisionSolverEntities.doc.md
  doc/CollisionSolverIsaac.doc.md
  src/CollisionSolver.var.s
  src/CollisionSolverEntities.lib.s
  src/CollisionSolverIsaac.lib.s
Labels: gameplay

#39 Display
  doc/check_inputs.doc.md
  doc/display.doc.md
  doc/display.init.doc.md
  doc/display.var.doc.md
  doc/sprite.var.doc.md
  src/check_inputs.s
  src/display.s
  src/init/display.init.s
  src/main.s
  src/sprites/fly.sprite
  src/sprites/rock.sprite
  src/var/display.var.s
  src/var/sprite.var.s
Labels: emulator-tested

#45 Implement Collision
  doc/CollisionSolverIsaac.doc.md
  doc/global.var.doc.md
  src/init/display_test.init.s
  src/init/global.init.s
  src/init/room.init.s.stub
  src/lib/CollisionSolverIsaac.lib.s
  src/lib/collision.lib.s
  src/main.s
  src/movement.s.stub
  src/var/collision.var.s
  src/var/global.var.s
Labels: gameplay

#61 We need to build a wall
  src/init/display_test.init.s
  src/init/global.init.s
  src/init/room.init.s.stub
  src/var/global.var.s
Labels: collision, emulator-tested

#71 quick and dirty fix
  src/lib/CollisionSolverEntities.lib.s
Labels: bug

#85 New struct Implementation
  doc/global.var.doc.md
  src/init/display_test.init.s
  src/init/global.init.s
  src/init/room.init.s.stub
  src/movement_and_collide.s
  src/var/global.var.s
Labels: enhancement

#88 add damage
  doc/movement_and_collide.doc.md
  src/init/display_test.init.s
  src/init/global.init.s
  src/init/room.init.s.stub
  src/movement_and_collide.s
Labels: collision, enhancement, gameplay

#91 Hitboxes
  src/init/global.init.s
  src/init/room.init.s.stub
  src/movement_and_collide.s
Labels: collision, emulator-tested

#90 Add Rng
  doc/rng.lib.doc.md
  doc/rng.var.doc.md
  src/body.s
  src/init/rng.init.s
  src/lib/rng.lib.s
  src/main.s
  src/var/rng.var.s
Labels: emulator-tested, enhancement

#97 Tears
  doc/global.var.doc.md
  src/var/global.var.s
Labels: enhancement

#107 Forgot something
  doc/rng.lib.doc.md
Labels: documentation

#106 Stack in WRAM
  src/main.s
Labels: console-tested, emulator-tested, enhancement
