Repository PainsPerdus/gboi-rocket, pull requests merged in 2020-07, with the labels that each got.

#112 Load maps
  doc/load_map.doc.md
  src/init/display_test.init.s
  src/init/global.init.s
  src/init/room.init.s.stub
  src/lib/load_blocking.lib.s
  src/lib/load_enemy.lib.s
  src/lib/load_map.lib.s
  src/lib/sprites.lib.s
  src/main.s
  src/rooms/basic.room
  src/sprites/pit_spritesheet.sprite
  src/var/global.var.s
  src/var/load_map.var.s
  src/var/sprite.var.s
Labels: emulator-tested, enhancement, level-design

#126 Load maps
  doc/load_map.doc.md
  doc/main.doc.md
  src/body.s
  src/check_collisions_isaac_objects.s
  src/init/changeRoom.init.s
  src/init/display.init.s
  src/init/global.init.s
  src/lib/display_doors.lib.s
  src/lib/display_room.lib.s
  src/lib/door_functions.lib.s
  src/lib/load_blocking.lib.s
  src/lib/load_complete_with_void.lib.s
  src/lib/load_doors.lib.s
  src/lib/load_enemy.lib.s
  src/lib/load_map.lib.s
  src/lib/stairs_function.lib.s
  src/main.s
  src/rooms/basic1.room
  src/rooms/correspondingIDAdress.room
  src/var/current_floor.var.s
  src/var/global.var.s
  src/var/load_map.var.s
  src/vblank/title_screen.vbl.s
Labels: level-design

#132 Octogones
  src/lib/load_doors.lib.s
  src/lib/load_enemy.lib.s
  src/lib/load_map.lib.s
  src/maps/map1.level1
  src/rooms/basic2.room
  src/rooms/basic6.room
  src/rooms/basic8.room
  src/tears_dmg.s
  src/var/load_map.var.s
Labels: gameplay

#140 reset tears when room changes
  src/lib/load_complete_with_void.lib.s
Labels: enhancement

#149 sounds like isaac's screaming
  src/lib/sfx.lib.s
Labels: emulator-tested, enhancement, sound
